theme: jekyll-theme-cayman
title: code-generation|code-gui
description: 代码生成工具
show_downloads: true
gitee:
  repository_url: https://gitee.com/LW_Ping/code4j
github:
  is_project_page: false
  jar_url: https://gitee.com/LW_Ping/code4j/attach_files/1141810/download/code4j.jar
  zip_url: https://gitee.com/LW_Ping/code4j/repository/archive/v1.1.1?format=zip

  
